/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessosRouteImport } from './routes/acessos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as FichasRouteImport } from './routes/fichas'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as AtividadesIndexRouteImport } from './routes/atividades.index'
import { Route as AtividadesIdRouteImport } from './routes/atividades.$id'
import { Route as EducandosIndexRouteImport } from './routes/educandos.index'
import { Route as EducandosIdRouteImport } from './routes/educandos.$id'
import { Route as EducandosNovoRouteImport } from './routes/educandos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessosRoute = AcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasRoute = FichasRouteImport.update({
  id: '/fichas',
  path: '/fichas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIndexRoute = AtividadesIndexRouteImport.update({
  id: '/atividades/',
  path: '/atividades/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIdRoute = AtividadesIdRouteImport.update({
  id: '/atividades/$id',
  path: '/atividades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EducandosIndexRoute = EducandosIndexRouteImport.update({
  id: '/educandos/',
  path: '/educandos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducandosIdRoute = EducandosIdRouteImport.update({
  id: '/educandos/$id',
  path: '/educandos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EducandosNovoRoute = EducandosNovoRouteImport.update({
  id: '/educandos/novo',
  path: '/educandos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/agenda': typeof AgendaRoute
  '/fichas': typeof FichasRoute
  '/indicadores': typeof IndicadoresRoute
  '/projetos': typeof ProjetosRoute
  '/atividades/$id': typeof AtividadesIdRoute
  '/educandos/$id': typeof EducandosIdRoute
  '/educandos/novo': typeof EducandosNovoRoute
  '/atividades/': typeof AtividadesIndexRoute
  '/educandos/': typeof EducandosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/agenda': typeof AgendaRoute
  '/fichas': typeof FichasRoute
  '/indicadores': typeof IndicadoresRoute
  '/projetos': typeof ProjetosRoute
  '/atividades/$id': typeof AtividadesIdRoute
  '/educandos/$id': typeof EducandosIdRoute
  '/educandos/novo': typeof EducandosNovoRoute
  '/atividades': typeof AtividadesIndexRoute
  '/educandos': typeof EducandosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/agenda': typeof AgendaRoute
  '/fichas': typeof FichasRoute
  '/indicadores': typeof IndicadoresRoute
  '/projetos': typeof ProjetosRoute
  '/atividades/$id': typeof AtividadesIdRoute
  '/educandos/$id': typeof EducandosIdRoute
  '/educandos/novo': typeof EducandosNovoRoute
  '/atividades/': typeof AtividadesIndexRoute
  '/educandos/': typeof EducandosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessos'
    | '/agenda'
    | '/fichas'
    | '/indicadores'
    | '/projetos'
    | '/atividades/$id'
    | '/educandos/$id'
    | '/educandos/novo'
    | '/atividades/'
    | '/educandos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessos'
    | '/agenda'
    | '/fichas'
    | '/indicadores'
    | '/projetos'
    | '/atividades/$id'
    | '/educandos/$id'
    | '/educandos/novo'
    | '/atividades'
    | '/educandos'
  id:
    | '__root__'
    | '/'
    | '/acessos'
    | '/agenda'
    | '/fichas'
    | '/indicadores'
    | '/projetos'
    | '/atividades/$id'
    | '/educandos/$id'
    | '/educandos/novo'
    | '/atividades/'
    | '/educandos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessosRoute: typeof AcessosRoute
  AgendaRoute: typeof AgendaRoute
  FichasRoute: typeof FichasRoute
  IndicadoresRoute: typeof IndicadoresRoute
  ProjetosRoute: typeof ProjetosRoute
  AtividadesIdRoute: typeof AtividadesIdRoute
  EducandosIdRoute: typeof EducandosIdRoute
  EducandosNovoRoute: typeof EducandosNovoRoute
  AtividadesIndexRoute: typeof AtividadesIndexRoute
  EducandosIndexRoute: typeof EducandosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessos': {
      id: '/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas': {
      id: '/fichas'
      path: '/fichas'
      fullPath: '/fichas'
      preLoaderRoute: typeof FichasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/': {
      id: '/atividades/'
      path: '/atividades'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AtividadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/$id': {
      id: '/atividades/$id'
      path: '/atividades/$id'
      fullPath: '/atividades/$id'
      preLoaderRoute: typeof AtividadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educandos/': {
      id: '/educandos/'
      path: '/educandos'
      fullPath: '/educandos/'
      preLoaderRoute: typeof EducandosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educandos/$id': {
      id: '/educandos/$id'
      path: '/educandos/$id'
      fullPath: '/educandos/$id'
      preLoaderRoute: typeof EducandosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educandos/novo': {
      id: '/educandos/novo'
      path: '/educandos/novo'
      fullPath: '/educandos/novo'
      preLoaderRoute: typeof EducandosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessosRoute: AcessosRoute,
  AgendaRoute: AgendaRoute,
  FichasRoute: FichasRoute,
  IndicadoresRoute: IndicadoresRoute,
  ProjetosRoute: ProjetosRoute,
  AtividadesIdRoute: AtividadesIdRoute,
  EducandosIdRoute: EducandosIdRoute,
  EducandosNovoRoute: EducandosNovoRoute,
  AtividadesIndexRoute: AtividadesIndexRoute,
  EducandosIndexRoute: EducandosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
